### PR TITLE
created a branch to PR

### PR DESCRIPTION
**Pull request by pariterre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pariterre** [comment]
@conda-forge-admin, please rerender

**Comment by pariterre** [comment]
@conda-forge-admin, please rerender

**Comment by pariterre** [comment]
@conda-forge/staged-recipes
Hi! There is this weird fail from Ninja which does not return useful information.. I tried to build locally and it works. If I "rerun" it fails again, but it randomly fails at another file
Any idea?

**Comment by pariterre** [comment]
@conda-forge-admin, please rerender

**Comment by pariterre** [comment]
@conda-forge-admin, please rerender

**Comment by nehaljwani** [comment]
@pariterre To use 2019, you need to follow https://conda-forge.org/docs/maintainer/knowledge_base.html#using-vs2019

**Comment by pariterre** [comment]
@nehaljwani 
Oh.. you are right... sorry :(

**Comment by pariterre** [comment]
@conda-forge-admin please rerender

**Comment by pariterre** [comment]
@conda-forge-admin please rerender

**Comment by pariterre** [comment]
@conda-forge-admin please rerender

**Pull request merged**
