### PR TITLE
Removed lib64 thing

### PR DESCRIPTION
**Pull request by pariterre**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pariterre** [comment]
@conda-forge/staged-recipes
Is there some way to see the log of the build created by this PR? Because the purpose of the PR was to ensure the library was installing in $PREFIX/lib instead of $PREFIX/lib64 on UNIX. However, even though the tests shows precisely this, the resulting package on anaconda is still installing in lib64 folder...

**Comment by beckermr** [comment]
You can look at the commits on master and check the status symbols there (the red x or green checkmark). This should take you to a github page that then has a small link at the bottom to the azure CI pages.

**Comment by pariterre** [comment]
@beckermr 
ok, then I am seeing the right one... 
```
Install the project...
-- Install configuration: "Release"
-- Installing: $PREFIX/lib/librbdl.so.2.6.0
-- Installing: $PREFIX/lib/librbdl.so
-- Installing: $PREFIX/include/rbdl/rbdl_config.h
-- Installing: $PREFIX/include/rbdl/Body.h
-- Installing: $PREFIX/include/rbdl/Constraints.h
-- Installing: $PREFIX/include/rbdl/Dynamics.h
-- Installing: $PREFIX/include/rbdl/Joint.h
-- Installing: $PREFIX/include/rbdl/Kinematics.h
-- Installing: $PREFIX/include/rbdl/Logging.h
-- Installing: $PREFIX/include/rbdl/Model.h
-- Installing: $PREFIX/include/rbdl/Quaternion.h
-- Installing: $PREFIX/include/rbdl/SpatialAlgebraOperators.h
-- Installing: $PREFIX/include/rbdl/compileassert.h
-- Installing: $PREFIX/include/rbdl/rbdl.h
-- Installing: $PREFIX/include/rbdl/rbdl_eigenmath.h
-- Installing: $PREFIX/include/rbdl/rbdl_math.h
-- Installing: $PREFIX/include/rbdl/rbdl_mathutils.h
-- Installing: $PREFIX/include/rbdl/rbdl_utils.h
-- Installing: $PREFIX/lib/pkgconfig/rbdl.pc
```
Do you have any idea why it install to lib64 on anaconda (```https://anaconda.org/conda-forge/rbdl/files```)?

**Comment by beckermr** [comment]
No, I do not. :/

**Comment by xhochy** [comment]
@pariterre You did a PR from this repo and the first commit of this PR was uploaded to anaconda as the new build. Later commits and the one from master skipped the upload as the version already existed. That's why it's always important to work on forks instead of the main repo.

**Comment by pariterre** [comment]
@xhochy 
Solved, thank you!

**Pull request merged**
