### PR TITLE
tried to add windows

### PR DESCRIPTION
**Pull request by pariterre**

### CODE REVIEW

**Comment by pariterre** [comment]
@conda-forge/staged-recipes 
Hi there! I am trying to add windows! I am almost there. Here is one of the error I think is the problem: ```nm.exe [...]\Kinematics.cc.obj: File format not recognized```. On internet they say that happens when something compiled in 32-bits is linked with a 64-bits. Do you think it is the case? Should I forget the idea of compiling for windows?
Thanks :)

**Comment by isuruf** [comment]
You can ignore that `nm` error

**Comment by isuruf** [comment]
You need to do `-DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%"^` for the tests to pass

**Comment by isuruf** [comment]
Also, add `-DCMAKE_BUILD_TYPE=Release` in both unix and windows build to build in Release mode instead of Debug mode

**Pull request merged**
